#-----------------------------------------
# Site settings
#-----------------------------------------
_merge: deep

title: Szilárd Nagy
baseURL: https://nszilard.github.io/
languageCode: en-gb

paginate: 6
enableEmoji:            true
enableGitInfo:          true
enableRobotsTXT:        true
enableInlineShortcodes: true
pygmentsUseClasses:     true
pygmentsCodefences:     true

#-----------------------------------------
# Module settings
#-----------------------------------------
module:
  imports:
  - path: github.com/nszilard/aurora
